// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7Rvh-3xnn-4Ha5i_ZPxWVEHca-lqpro',
    appId: '1:60395839312:web:9ab1e0a07a8493ae9f9655',
    messagingSenderId: '60395839312',
    projectId: 'map-exp-6-f75e4',
    authDomain: 'map-exp-6-f75e4.firebaseapp.com',
    storageBucket: 'map-exp-6-f75e4.firebasestorage.app',
    measurementId: 'G-DLGFEYPQMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wZex8icWrVhqzrCTcC28CPGUULSQZPo',
    appId: '1:60395839312:android:36e887e093481ba89f9655',
    messagingSenderId: '60395839312',
    projectId: 'map-exp-6-f75e4',
    storageBucket: 'map-exp-6-f75e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifn-V8YlThHhLg8dELSoK5O5QFRMGxAM',
    appId: '1:60395839312:ios:b0e80663c7536fcc9f9655',
    messagingSenderId: '60395839312',
    projectId: 'map-exp-6-f75e4',
    storageBucket: 'map-exp-6-f75e4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifn-V8YlThHhLg8dELSoK5O5QFRMGxAM',
    appId: '1:60395839312:ios:b0e80663c7536fcc9f9655',
    messagingSenderId: '60395839312',
    projectId: 'map-exp-6-f75e4',
    storageBucket: 'map-exp-6-f75e4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm7Rvh-3xnn-4Ha5i_ZPxWVEHca-lqpro',
    appId: '1:60395839312:web:92342e2bd06781a99f9655',
    messagingSenderId: '60395839312',
    projectId: 'map-exp-6-f75e4',
    authDomain: 'map-exp-6-f75e4.firebaseapp.com',
    storageBucket: 'map-exp-6-f75e4.firebasestorage.app',
    measurementId: 'G-CP78EXXJF3',
  );
}
